name: LockedItems
version: 3.5
main: net.minefs.LockedItems.Main
authors: [MasterClaus, tranlong5252]
depend: [DeathDropsAPI]
softdepend: [ASkyBlock]
api-version: 1.16
commands:
 lockeditems:
  description: /<command> [reload]
  permission: lockeditems.admin
  aliases: [li, khoa, lock, lockitem]
permissions:
 lockeditems.*:
  default: op
  children:
   lockeditems.admin: true
   lockeditems.ignore: true